kind: pipeline
type: docker
name: default


steps:
  - name: test
    image: golang:1.13
    commands:
      - go test ./cmd/... ./internal/...
      - go vet ./cmd/... ./internal/...
  - name: lint
    image: cytopia/golint
    commands:
      - golint -set_exit_status ./cmd/... ./internal/...
  - name: build
    image: golang:1.13
    commands:
      - go build -o build/drone-helm cmd/drone-helm/main.go
  - name: publish_linux_amd64
    image: plugins/docker
    settings:
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo:
        from_secret: plugin_repo
      dockerfile: Dockerfile
    when:
      event: [ tag, push ]
